services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pgdata:
