/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoAboutRouteImport } from './routes/demo/about'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AppWorkshopsRouteImport } from './routes/_app/workshops'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiInitialSplatRouteImport } from './routes/api/initial.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppInventoryPurchaseOrdersRouteImport } from './routes/_app/inventory.purchase-orders'
import { Route as AppInventoryProductsRouteImport } from './routes/_app/inventory.products'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin.users.index'
import { Route as AdminAdminUsersNewRouteImport } from './routes/_admin/admin.users.new'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/drizzle',
  path: '/drizzle',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/better-auth',
  path: '/better-auth',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAboutRoute = DemoAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DemoRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkshopsRoute = AppWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInitialSplatRoute = ApiInitialSplatRouteImport.update({
  id: '/api/initial/$',
  path: '/api/initial/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryPurchaseOrdersRoute =
  AppInventoryPurchaseOrdersRouteImport.update({
    id: '/inventory/purchase-orders',
    path: '/inventory/purchase-orders',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersNewRoute = AdminAdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/about': typeof AppAboutRoute
  '/workshops': typeof AppWorkshopsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/': typeof DemoIndexRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/initial/$': typeof ApiInitialSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/workshops': typeof AppWorkshopsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo': typeof DemoIndexRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/initial/$': typeof ApiInitialSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/admin/users/new': typeof AdminAdminUsersNewRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/workshops': typeof AppWorkshopsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/_app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/_app/inventory/products': typeof AppInventoryProductsRoute
  '/_app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/initial/$': typeof ApiInitialSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_admin/admin/users/new': typeof AdminAdminUsersNewRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/about'
    | '/workshops'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/demo/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/'
    | '/inventory/products'
    | '/inventory/purchase-orders'
    | '/settings/account'
    | '/api/auth/$'
    | '/api/initial/$'
    | '/api/trpc/$'
    | '/admin/'
    | '/inventory/'
    | '/admin/users/new'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/workshops'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/demo/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo'
    | '/inventory/products'
    | '/inventory/purchase-orders'
    | '/settings/account'
    | '/api/auth/$'
    | '/api/initial/$'
    | '/api/trpc/$'
    | '/admin'
    | '/inventory'
    | '/admin/users/new'
    | '/admin/users'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/demo'
    | '/_app/about'
    | '/_app/workshops'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/demo/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/_app/'
    | '/demo/'
    | '/_app/inventory/products'
    | '/_app/inventory/purchase-orders'
    | '/_app/settings/account'
    | '/api/auth/$'
    | '/api/initial/$'
    | '/api/trpc/$'
    | '/_admin/admin/'
    | '/_app/inventory/'
    | '/_admin/admin/users/new'
    | '/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInitialSplatRoute: typeof ApiInitialSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/about': {
      id: '/demo/about'
      path: '/about'
      fullPath: '/demo/about'
      preLoaderRoute: typeof DemoAboutRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workshops': {
      id: '/_app/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof AppWorkshopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/initial/$': {
      id: '/api/initial/$'
      path: '/api/initial/$'
      fullPath: '/api/initial/$'
      preLoaderRoute: typeof ApiInitialSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/purchase-orders': {
      id: '/_app/inventory/purchase-orders'
      path: '/inventory/purchase-orders'
      fullPath: '/inventory/purchase-orders'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/new': {
      id: '/_admin/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminAdminUsersNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersNewRoute: typeof AdminAdminUsersNewRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersNewRoute: AdminAdminUsersNewRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppWorkshopsRoute: typeof AppWorkshopsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryPurchaseOrdersRoute: typeof AppInventoryPurchaseOrdersRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppWorkshopsRoute: AppWorkshopsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryPurchaseOrdersRoute: AppInventoryPurchaseOrdersRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DemoRouteChildren {
  DemoAboutRoute: typeof DemoAboutRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAboutRoute: DemoAboutRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInitialSplatRoute: ApiInitialSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
